"""Convert the designer's sprite sheets (art/src) into WoW-ready textures.

Source sheets: 128x128 cells, 10 columns, frames left-to-right, top-to-bottom.
Output: Media/Anim/<key>_<page>.tga pages of 8x8 cells (1024x1024, power of two)
plus AnimData.lua describing every animation for the addon.

Run from the repo root:  python tools/build_anims.py
Requires Pillow.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "art", "src")
OUT = os.path.join(ROOT, "Media", "Anim")
LUA = os.path.join(ROOT, "AnimData.lua")

CELL = 128
SRC_COLS = 10
PAGE_COLS = 8
ADDON_PATH = "Interface\\AddOns\\Blightfall\\Media\\Anim\\"

# key -> (source file relative to art/src, frame count)
ANIMS = {
    "reaper_loading": ("reaper/Reaper_Loading.png", 150),
    "reaper_ready": ("reaper/Reaper_Ready.png", 60),
    "reaper_idle": ("reaper/Reaper_idle.png", 60),
    "reaper_onuse": ("reaper/Reaper_Onuse.png", 15),
    "blight_loading": ("blightfall/Blightfall_Loading.png", 150),
    "blight_ready": ("blightfall/Blightfall_Ready.png", 60),
    "blight_idle": ("blightfall/Blightfall_idle.png", 60),
    "blight_onuse": ("blightfall/Blightfall_Onuse.png", 15),
}

PUTREFY_VARIANTS = ["blod", "blod-prf", "frst", "frst-prf", "uhly", "uhly-prf"]
for variant in PUTREFY_VARIANTS:
    color, _, style = variant.partition("-")
    for size in ("big", "sml"):
        stem = f"{color}-{style}-{size}" if style else f"{color}-{size}"
        key = f"putrefy_{variant.replace('-', '_')}_{size}"
        ANIMS[key + "_idle"] = (f"putrefy/{stem}-idle.png", 60)
        ANIMS[key + "_onuse"] = (f"putrefy/{stem}-Onuse.png", 15)


def page_size(frames):
    """Smallest power-of-two square page (in cells per side) that fits the frames, max 8."""
    side = 1
    while side * side < frames and side < PAGE_COLS:
        side *= 2
    return side


def build(key, rel, count):
    sheet = Image.open(os.path.join(SRC, rel)).convert("RGBA")
    cells = []
    for i in range(count):
        x, y = (i % SRC_COLS) * CELL, (i // SRC_COLS) * CELL
        cells.append(sheet.crop((x, y, x + CELL, y + CELL)))

    per_page = PAGE_COLS * PAGE_COLS
    pages = []
    for p in range(0, count, per_page):
        chunk = cells[p:p + per_page]
        side = page_size(len(chunk))
        page = Image.new("RGBA", (side * CELL, side * CELL), (0, 0, 0, 0))
        for j, cell in enumerate(chunk):
            page.paste(cell, ((j % side) * CELL, (j // side) * CELL))
        name = f"{key}_{len(pages) + 1}"
        page.save(os.path.join(OUT, name + ".tga"))
        pages.append((name, side))
    return pages


def main():
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith(".tga"):
            os.remove(os.path.join(OUT, f))

    lines = [
        "-- Generated by tools/build_anims.py. Do not edit by hand.",
        "local _, ns = ...",
        "ns.AnimData = {",
    ]
    for key, (rel, count) in ANIMS.items():
        pages = build(key, rel, count)
        lua_path = ADDON_PATH.replace("\\", "\\\\")
        page_list = ", ".join(f'{{"{lua_path}{n}", {side}}}' for n, side in pages)
        lines.append(f"    {key} = {{frames = {count}, perPage = {PAGE_COLS * PAGE_COLS}, pages = {{{page_list}}}}},")
    lines.append("}")
    lines.append("ns.PutrefyVariants = {" + ", ".join(f'"{v.replace("-", "_")}"' for v in PUTREFY_VARIANTS) + "}")
    with open(LUA, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Built {len(ANIMS)} animations into {OUT}")


if __name__ == "__main__":
    main()
