"""Convert the designer's sprite sheets (art/src) into WoW-ready textures.

Source sheets are grids of square cells, frames left-to-right, top-to-bottom.
Output: Media/Anim/<key>_<page>.tga pages of up to 8x8 cells plus AnimData.lua
describing every animation for the addon.

Run from the repo root:  python tools/build_anims.py
Requires Pillow.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "art", "src")
OUT = os.path.join(ROOT, "Media", "Anim")
LUA = os.path.join(ROOT, "AnimData.lua")

PAGE_COLS = 8
ADDON_PATH = "Interface\\AddOns\\Blightfall\\Media\\Anim\\"

# key -> dict(src, frames, cols=source columns, cell=source cell px,
#             out=output cell px). Output cells are what the addon draws.
ANIMS = {}


def add(key, src, frames, cols=10, cell=128, out=128):
    ANIMS[key] = dict(src=src, frames=frames, cols=cols, cell=cell, out=out)


for stage, folder, name in (("reaper", "reaper", "Reaper"), ("blight", "blightfall", "Blightfall")):
    add(f"{stage}_loading", f"{folder}/{name}_Loading.png", 150)
    add(f"{stage}_ready", f"{folder}/{name}_Ready.png", 60)
    add(f"{stage}_idle", f"{folder}/{name}_idle.png", 60)
    add(f"{stage}_onuse", f"{folder}/{name}_Onuse.png", 15)

PUTREFY_VARIANTS = ["blod", "blod-prf", "frst", "frst-prf", "uhly", "uhly-prf"]
for variant in PUTREFY_VARIANTS:
    color, _, style = variant.partition("-")
    for size in ("big", "sml"):
        stem = f"{color}-{style}-{size}" if style else f"{color}-{size}"
        key = f"putrefy_{variant.replace('-', '_')}_{size}"
        add(key + "_idle", f"putrefy/{stem}-idle.png", 60)
        add(key + "_onuse", f"putrefy/{stem}-Onuse.png", 15)

# Perfect-combo celebration: 24 columns of 188px cells, downscaled to 128 so
# the 528 frames stay within a sane texture budget.
add("celebration", "celebration/helios_rap.png", 528, cols=24, cell=188, out=128)


def page_size(frames):
    """Smallest power-of-two square page (in cells per side) that fits the frames."""
    side = 1
    while side * side < frames and side < PAGE_COLS:
        side *= 2
    return side


def build(key, spec):
    sheet = Image.open(os.path.join(SRC, spec["src"])).convert("RGBA")
    cell, out, cols = spec["cell"], spec["out"], spec["cols"]

    cells = []
    for i in range(spec["frames"]):
        x, y = (i % cols) * cell, (i // cols) * cell
        frame = sheet.crop((x, y, x + cell, y + cell))
        if out != cell:
            frame = frame.resize((out, out), Image.LANCZOS)
        cells.append(frame)

    per_page = PAGE_COLS * PAGE_COLS
    pages = []
    for p in range(0, len(cells), per_page):
        chunk = cells[p:p + per_page]
        side = page_size(len(chunk))
        page = Image.new("RGBA", (side * out, side * out), (0, 0, 0, 0))
        for j, c in enumerate(chunk):
            page.paste(c, ((j % side) * out, (j // side) * out))
        name = f"{key}_{len(pages) + 1}"
        page.save(os.path.join(OUT, name + ".tga"))
        pages.append((name, side))
    return pages


def main():
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith(".tga"):
            os.remove(os.path.join(OUT, f))

    lua_path = ADDON_PATH.replace("\\", "\\\\")
    lines = [
        "-- Generated by tools/build_anims.py. Do not edit by hand.",
        "local _, ns = ...",
        "ns.AnimData = {",
    ]
    for key, spec in ANIMS.items():
        pages = build(key, spec)
        page_list = ", ".join(f'{{"{lua_path}{n}", {side}}}' for n, side in pages)
        lines.append(
            f"    {key} = {{frames = {spec['frames']}, cell = {spec['out']}, "
            f"perPage = {PAGE_COLS * PAGE_COLS}, pages = {{{page_list}}}}},"
        )
    lines.append("}")
    lines.append("ns.PutrefyVariants = {" + ", ".join(f'"{v.replace("-", "_")}"' for v in PUTREFY_VARIANTS) + "}")
    with open(LUA, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Built {len(ANIMS)} animations into {OUT}")


if __name__ == "__main__":
    main()
