"""Convert the designer's sprite sheets (art/src) into WoW-ready textures.

Source sheets are grids of square cells, frames left-to-right, top-to-bottom.
Output: Media/Anim/<key>_<page>.tga atlas pages plus AnimData.lua describing
every animation for the addon.

Each page holds a square grid of cells and is padded to a power-of-two square,
which is what WoW is happiest loading. AnimData stores the cells-per-row and
the texture coordinate step so the addon can slice any cell size.

Run from the repo root:  python tools/build_anims.py
Requires Pillow.
"""
import math
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "art", "src")
OUT = os.path.join(ROOT, "Media", "Anim")
LUA = os.path.join(ROOT, "AnimData.lua")

MAX_TEXTURE = 2048
ADDON_PATH = "Interface\\AddOns\\Blightfall\\Media\\Anim\\"

ANIMS = {}


def add(key, src, cols=10, cell=128, out=None):
    """Frame counts are read from the sheet; out defaults to the cell size."""
    ANIMS[key] = dict(src=src, cols=cols, cell=cell, out=out or cell)


for stage, folder, name in (("reaper", "reaper", "Reaper"), ("blight", "blightfall", "Blightfall")):
    add(f"{stage}_loading", f"{folder}/{name}_Loading.png")
    add(f"{stage}_ready", f"{folder}/{name}_Ready.png")
    add(f"{stage}_idle", f"{folder}/{name}_idle.png")
    add(f"{stage}_onuse", f"{folder}/{name}_Onuse.png")

PUTREFY_VARIANTS = ["blod", "blod-prf", "frst", "frst-prf", "uhly", "uhly-prf"]
for variant in PUTREFY_VARIANTS:
    color, _, style = variant.partition("-")
    for size in ("big", "sml", "xs"):
        stem = f"{color}-{style}-{size}" if style else f"{color}-{size}"
        key = f"putrefy_{variant.replace('-', '_')}_{size}"
        cell = 80 if size == "xs" else 128
        add(key + "_idle", f"putrefy/{stem}-idle.png", cell=cell)
        add(key + "_onuse", f"putrefy/{stem}-Onuse.png", cell=cell)

# Perfect-combo celebration, kept at its native 188px cells.
add("celebration", "celebration/helios_rap.png", cols=24, cell=188)


# The square tile WoW shows beside the addon in its list.
LOGO_SRC = os.path.join(ROOT, "art", "logo.png")
LOGO_OUT = os.path.join(ROOT, "Media", "Logo.tga")
LOGO_SIZE = 128


def build_logo():
    if not os.path.exists(LOGO_SRC):
        return
    img = Image.open(LOGO_SRC).convert("RGBA")
    img.resize((LOGO_SIZE, LOGO_SIZE), Image.LANCZOS).save(LOGO_OUT)
    print(f"Logo written to {LOGO_OUT}")


def next_pot(v):
    p = 1
    while p < v:
        p *= 2
    return p


def build(key, spec):
    sheet = Image.open(os.path.join(SRC, spec["src"])).convert("RGBA")
    cell, out, cols = spec["cell"], spec["out"], spec["cols"]

    # The sheet's grid may have spare cells at the end, so the real length is
    # the last one that still has something drawn in it.
    total = (sheet.size[0] // cell) * (sheet.size[1] // cell)
    count = 0
    for i in range(total):
        x, y = (i % cols) * cell, (i // cols) * cell
        if sheet.crop((x, y, x + cell, y + cell)).getbbox():
            count = i + 1
    spec["frames"] = count

    frames = []
    for i in range(count):
        x, y = (i % cols) * cell, (i // cols) * cell
        frame = sheet.crop((x, y, x + cell, y + cell))
        if out != cell:
            frame = frame.resize((out, out), Image.LANCZOS)
        frames.append(frame)

    max_cols = max(1, MAX_TEXTURE // out)
    per_page = max_cols * max_cols

    pages = []
    for p in range(0, len(frames), per_page):
        chunk = frames[p:p + per_page]
        page_cols = min(max_cols, math.ceil(math.sqrt(len(chunk))))
        tex = next_pot(page_cols * out)
        page = Image.new("RGBA", (tex, tex), (0, 0, 0, 0))
        for j, f in enumerate(chunk):
            page.paste(f, ((j % page_cols) * out, (j // page_cols) * out))
        name = f"{key}_{len(pages) + 1}"
        page.save(os.path.join(OUT, name + ".tga"))
        pages.append((name, page_cols, out / tex))
    return per_page, pages


def main():
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith(".tga"):
            os.remove(os.path.join(OUT, f))

    lua_path = ADDON_PATH.replace("\\", "\\\\")
    lines = [
        "-- Generated by tools/build_anims.py. Do not edit by hand.",
        "local _, ns = ...",
        "ns.AnimData = {",
    ]
    total = 0
    for key, spec in ANIMS.items():
        per_page, pages = build(key, spec)
        total += sum(os.path.getsize(os.path.join(OUT, n + ".tga")) for n, _, _ in pages)
        page_list = ", ".join(f'{{"{lua_path}{n}", {c}, {uv:.10g}}}' for n, c, uv in pages)
        lines.append(
            f"    {key} = {{frames = {spec['frames']}, cell = {spec['out']}, "
            f"perPage = {per_page}, pages = {{{page_list}}}}},"
        )
    lines.append("}")
    lines.append("ns.PutrefyVariants = {" + ", ".join(f'"{v.replace("-", "_")}"' for v in PUTREFY_VARIANTS) + "}")
    with open(LUA, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("\n".join(lines) + "\n")
    build_logo()
    print(f"Built {len(ANIMS)} animations, {total / 1024 / 1024:.0f} MB of textures")


if __name__ == "__main__":
    main()
